alpaca:
  key: "ENV:ALPACA_API_KEY"
  secret: "ENV:ALPACA_API_SECRET"

fmp:
  apikey: "ENV:FMP_API_KEY"

polygon:
  key: "ENV:POLYGON_KEY"

fred:
  key: "ENV:FRED_KEY"

reddit:
  client_id: "ENV:REDDIT_CLIENT_ID"
  secret: "ENV:REDDIT_SECRET"
  user_agent: "ENV:REDDIT_USER_AGENT"
